version: "2"
services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: client
    build: ./client
    ports:
      - "3001:80"